version: '3.8'

services:
  api:
    image: ratelimiter
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["-port=9000", "-redis_addr=redis:6379", "-ratelimiter_strategy=fixedwindow", "-fixed_window_size=60", "-fixed_window_limit=60"]
    depends_on: 
      - redis
    ports: 
      - "9000:9000"
  redis:
    image: redis:6.0.10-alpine
